name:                cabal-to-hie-yaml
version:             0.1.0.0
github:              "Siprj/cabal-to-hie-yaml"
license:             BSD3
author:              "Jan Sipr"
maintainer:          "sipr.jan@gmail.com"
copyright:           "2020 Jan Sipr"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - base >= 4.7 && < 5
  - Cabal
  - directory
  - filepath
  - lens
  - text

library:
  source-dirs: src

executables:
  cabal-to-hie-yaml-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cabal-to-hie-yaml

tests:
  simple-hpack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cabal-to-hie-yaml
